### PR TITLE
#5 Feature Request - Add support for JSON with Comments

### PR DESCRIPTION
**Pull request by giddingsra0**
# Description of Changes

- Added support for JSON with Comments using `comment-json` NPM package ([see package here](https://www.npmjs.com/package/comment-json))
- Formatted `extension.ts` using prettier config + VS Code autoformatter

# Related Issue
#5 

# Testing Done
- tested locally using both regular JSON and JSON file with comments
    - both render as expected
- Unit tests also still pass

### CODE REVIEW

**Comment by giddingsra0** [comment]
@ccimage This is a great extension. Once this new support is live, I will be using it almost daily. Please let me know if you have any questions or anything.

**Comment by ElijahSink** [comment]
I'd love to see this added as well!

**Comment by giddingsra0** [comment]
@ccimage Any time estimate on when this could get added?

**Comment by ccimage** [comment]
ok, i will publish a new version

**Pull request merged**
